version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    network_mode: services_default

    # keep the container alive
    command: sleep infinity